apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: collect-td-feed
  name: collect-td-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collect-td-feed
  template:
    metadata:
      labels:
        app: collect-td-feed
    spec:
      containers:
      - image: vandry/collect_td_feed
        command:
          - python
          - "collect_td_feed.py"
          - "/networkrail.credentials/credentials"
          - "https://td-feed-spool.sos-ch-dk-2.exo.io/"
        volumeMounts:
          - name: networkrail-credentials
            readOnly: true
            mountPath: "/networkrail.credentials"
          - name: s3-credentials
            readOnly: true
            mountPath: "/root/.aws"
        name: collect-td-feed
        ports:
        - containerPort: 3000
      volumes:
        - name: networkrail-credentials
          secret:
            secretName: networkrail.credentials
        - name: s3-credentials
          secret:
            secretName: s3.credentials
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: collect-td-feed
spec:
  selector:
    app: collect-td-feed
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
