[package]
name = "td-archive-server"
version = "0.1.0"
edition = "2021"

[dependencies]
array-init = "2.1"
async-stream = "0.3"
boxcar = "0.2"
bytes = "1.6"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
comprehensive = { version = "0.9" }
comprehensive_grpc = { version = "0.9", features = ["tls"] }
comprehensive_http = { version = "0.4", features = ["tls"] }
comprehensive_s3 = { version = "0.3" }
comprehensive_spiffe = { version = "0.4" }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
lru = "0.12"
openssl = { version = "0.10", features = ["vendored"] }  # for musl build
prometheus = "0.14"
prost = "0.14"
prost-types = "0.14"
regex = "1.10"
rust-s3 = "0.37"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "signal"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.14"
tonic-prost = "0.14"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
xz = "0.1"

[build-dependencies]
tonic-prost-build = "0.14"

[[bin]]
name = "mktdarchive"
path = "src/mktdarchive.rs"

[[bin]]
name = "td-archive-backup"
path = "src/td-archive-backup.rs"
