apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: td-archive-server
  name: td-archive-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: td-archive-server
  template:
    metadata:
      labels:
        app: td-archive-server
    spec:
      containers:
      - name: td-archive-server
        image: vandry/td_feed_archive
        command:
        - "/td-archive-server"
        - "https://sos-ch-dk-2.exo.io"
        - "ch-dk-2"
        - "td-archive"
        - "http://collect-td-feed:3000"
        - "[::]:3001"
        volumeMounts:
          - name: s3-credentials
            readOnly: true
            mountPath: "/root/.aws"
        ports:
        - containerPort: 3001
        env:
        - name: RUST_LOG
          value: info
      volumes:
        - name: s3-credentials
          secret:
            secretName: s3.credentials
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: td-archive
spec:
  selector:
    app: td-archive-server
  ports:
    - port: 3001
      targetPort: 3001
  type: LoadBalancer
