apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: td-archive-server
  name: td-archive-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: td-archive-server
  template:
    metadata:
      labels:
        app: td-archive-server
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
        server-diag-port: "1444"
        server-identity: spiffe://vandry.org/ns/default/pod-label/app/td-archive-server
    spec:
      containers:
      - name: td-archive-server
        image: vandry/td_feed_archive
        command:
        - "/td-archive-server"
        - "--s3-endpoint=https://sos-ch-dk-2.exo.io"
        - "--s3-region-name=ch-dk-2"
        - "--bucket-name=td-archive"
        - "--live-feed-uri=http://collect-td-feed:3000"
        - "--grpc-port=3001"
        - "--grpcs-port=1443"
        - "--diag-https-port=1444"
        - "--diag-http-port=9090"
        livenessProbe:
          grpc:
            port: 3001
            service: ""
        readinessProbe:
          grpc:
            port: 3001
            service: "ready"
        volumeMounts:
          - name: s3-credentials
            readOnly: true
            mountPath: "/root/.aws"
          - name: spire-agent-socket
            mountPath: /run/spire/sockets
            readOnly: true
        ports:
        - containerPort: 3001
        - containerPort: 9090
        - containerPort: 1443
        - containerPort: 1444
        env:
        - name: RUST_LOG
          value: info
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
      volumes:
        - name: s3-credentials
          secret:
            secretName: s3.credentials
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: td-archive
spec:
  selector:
    app: td-archive-server
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
